"""
Django settings for techcrunch_scraper_with_django project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from .local_settings import *
import os
from enum import Enum

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # TrustedApps

    # My Apss
    'techcrunch.apps.TechcrunchConfig',

    # Third-party Apps
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techcrunch_scraper_with_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techcrunch_scraper_with_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User constants


TIME_OUT = 15
DATA_PER_PAGE = '&per_page=100'

BASE_URL = 'https://www.techcrunch.com/'
JSON_PATH = 'wp-json/wp/v2/'
URL_FOR_SCRAPE = (BASE_URL + JSON_PATH + '{field}{filter_field}{filter_value}'
                                         '{data_per_page}'
                                         '{page}'
                                         '{envelope}'
                                         '{embed}'

                  )

SEARCH_BASE_URL = 'https://search.techcrunch.com/'
SEARCH_URL = (SEARCH_BASE_URL + 'search?p={keyword}&b={page}1')


class ItemTypes(Enum):
    POST = 'posts'
    CATEGORY = 'categories'
    AUTHOR = 'users'


class ItemAttributeTypes(Enum):
    ID = '/'
    SLUG = '?slug='
    CATEGORY = '?categories='
    NONE = ''


class EnvelopeStatuses(Enum):
    TRUE = '&_envelope=true'
    FALSE = '&_envelope=false'


class EmbedStatuses(Enum):
    TRUE = '&_embed=true'
    FALSE = '&_embed=false'
    NONE = ''


class AutoScrapLastPage(Enum):
    POST = 499
    CATEGORY = 3
    AUTHOR = 7
