# Generated by Django 4.2 on 2024-04-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id_on_techcrunch', models.CharField(max_length=20, verbose_name='Title')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
                ('avatar_link', models.CharField(max_length=250, verbose_name='Position')),
                ('avatar_image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id_on_techcrunch', models.CharField(max_length=20, verbose_name='Title')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('post_count', models.CharField(max_length=250, verbose_name='Post count')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=250, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id_on_techcrunch', models.CharField(max_length=20, verbose_name='ID on Techcrunch')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
                ('image_link', models.CharField(max_length=250, verbose_name='Image link')),
                ('image', models.ImageField(upload_to='images')),
                ('authors', models.ManyToManyField(related_name='posts', to='techcrunch.author')),
                ('categories', models.ManyToManyField(related_name='posts', to='techcrunch.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='SearchByKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('page_count', models.IntegerField(default=5, verbose_name='Page count')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='techcrunch.keyword')),
            ],
            options={
                'verbose_name': 'Search By Keyword',
                'verbose_name_plural': 'Search By Keywords',
            },
        ),
        migrations.CreateModel(
            name='PostSearchByKeywordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.CharField(max_length=250, verbose_name='Title')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is scraped')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='techcrunch.post')),
                ('search_by_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_search_by_keyword_items', to='techcrunch.searchbykeyword')),
            ],
            options={
                'verbose_name': 'Post Search By Keyword Item',
                'verbose_name_plural': 'Post Search By Keyword Items',
            },
        ),
    ]
