# Generated by Django 4.2 on 2024-04-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=250, verbose_name='field')),
            ],
            options={
                'verbose_name': 'Auto scrap',
                'verbose_name_plural': 'Auto scrap',
            },
        ),
        migrations.AlterField(
            model_name='postsearchbykeyworditem',
            name='search_by_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_search_by_keyword_items', to='techcrunch.searchbykeyword'),
        ),
        migrations.AlterField(
            model_name='postsearchbykeyworditem',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='AutoScrapPostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is scraped')),
                ('auto_scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_auto_scraps', to='techcrunch.autoscrap')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_auto_scraps', to='techcrunch.post')),
            ],
            options={
                'verbose_name': 'Auto Scrap Post Item',
                'verbose_name_plural': 'Auto Scrap Post Items',
            },
        ),
        migrations.CreateModel(
            name='AutoScrapCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is scraped')),
                ('auto_scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_auto_scraps', to='techcrunch.autoscrap')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_auto_scraps', to='techcrunch.category')),
            ],
            options={
                'verbose_name': 'Auto Scrap Category Item',
                'verbose_name_plural': 'Auto Scrap Category Items',
            },
        ),
        migrations.CreateModel(
            name='AutoScrapAuthorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is scraped')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_auto_scraps', to='techcrunch.author')),
                ('auto_scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_auto_scraps', to='techcrunch.autoscrap')),
            ],
            options={
                'verbose_name': 'Auto Scrap Author Item',
                'verbose_name_plural': 'Auto Scrap Author Items',
            },
        ),
    ]
