# Generated by Django 4.2 on 2024-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0002_autoscrap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsearchbykeyworditem',
            name='title',
        ),
        migrations.AlterField(
            model_name='author',
            name='id_on_techcrunch',
            field=models.CharField(max_length=20, verbose_name='ID on Techcrunch'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_on_techcrunch',
            field=models.CharField(max_length=20, verbose_name='ID on Techcrunch'),
        ),
    ]
