# Generated by Django 4.2 on 2024-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0003_remove_postsearchbykeyworditem_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoscrappostitem',
            name='slug',
        ),
        migrations.AddField(
            model_name='autoscrap',
            name='page_count',
            field=models.IntegerField(default=5, verbose_name='Page count'),
        ),
    ]
