# Generated by Django 4.2 on 2024-04-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0004_remove_autoscrappostitem_slug_autoscrap_page_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoscrapauthoritem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='autoscrapcategoryitem',
            name='slug',
        ),
    ]
