# Generated by Django 4.2 on 2024-04-12 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techcrunch', '0006_remove_post_authors_remove_post_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoscrapauthoritem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='autoscrapcategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='autoscrappostitem',
            name='post',
        ),
        migrations.AddField(
            model_name='autoscrap',
            name='page_start',
            field=models.IntegerField(default=1, verbose_name='Page count'),
        ),
        migrations.AddField(
            model_name='autoscrapauthoritem',
            name='authors',
            field=models.ManyToManyField(related_name='auto_scrap_author_items', to='techcrunch.author', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='autoscrapcategoryitem',
            name='categories',
            field=models.ManyToManyField(related_name='auto_scrap_category_items', to='techcrunch.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='autoscrappostitem',
            name='posts',
            field=models.ManyToManyField(related_name='auto_scrap_category_items', to='techcrunch.post', verbose_name='Posts'),
        ),
        migrations.AddField(
            model_name='searchbykeyword',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='searches', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoscrapauthoritem',
            name='auto_scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_scrap_author_items', to='techcrunch.autoscrap', verbose_name='Auto Scrap'),
        ),
        migrations.AlterField(
            model_name='autoscrapcategoryitem',
            name='auto_scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_scrap_category_items', to='techcrunch.autoscrap', verbose_name='Auto Scrap'),
        ),
        migrations.AlterField(
            model_name='autoscrappostitem',
            name='auto_scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_scrap_post_items', to='techcrunch.autoscrap', verbose_name='Auto Scrap'),
        ),
        migrations.AlterField(
            model_name='postauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_authors', to='techcrunch.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='postauthor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_authors', to='techcrunch.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='techcrunch.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='techcrunch.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postsearchbykeyworditem',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_search_by_keyword_items', to='techcrunch.post', verbose_name='Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsearchbykeyworditem',
            name='search_by_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_search_by_keyword_items', to='techcrunch.searchbykeyword', verbose_name='Search By Keyword'),
        ),
        migrations.AlterField(
            model_name='searchbykeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='techcrunch.keyword', verbose_name='Keyword'),
        ),
    ]
