# Generated by Django 4.2 on 2024-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0007_remove_autoscrapauthoritem_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbykeyword',
            name='user',
        ),
    ]
