# Generated by Django 4.2 on 2024-04-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0008_remove_searchbykeyword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoscrapauthoritem',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='auto_scrap_author_items', to='techcrunch.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='autoscrapcategoryitem',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='auto_scrap_category_items', to='techcrunch.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='autoscrappostitem',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='auto_scrap_category_items', to='techcrunch.post', verbose_name='Posts'),
        ),
        migrations.AlterField(
            model_name='postsearchbykeyworditem',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_search_by_keyword_items', to='techcrunch.post', verbose_name='Post'),
        ),
    ]
