# Generated by Django 4.2 on 2024-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0010_alter_post_image_link_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
