# Generated by Django 4.2 on 2024-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0012_remove_author_avatar_image_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoscrapauthoritem',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='auto_scrap_author_items', to='techcrunch.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='autoscrapcategoryitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='auto_scrap_category_items', to='techcrunch.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='autoscrappostitem',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='auto_scrap_category_items', to='techcrunch.post', verbose_name='Posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, max_length=250, verbose_name='Image link'),
        ),
    ]
