# Generated by Django 4.2 on 2024-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0013_alter_autoscrapauthoritem_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar_link',
            field=models.URLField(max_length=250, verbose_name='Position'),
        ),
    ]
