# Generated by Django 4.2 on 2024-04-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0014_alter_author_avatar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscrapauthoritem',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='Fail count'),
        ),
        migrations.AddField(
            model_name='autoscrapcategoryitem',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='Fail count'),
        ),
        migrations.AddField(
            model_name='autoscrappostitem',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='Fail count'),
        ),
        migrations.AddField(
            model_name='postsearchbykeyworditem',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='Fail count'),
        ),
    ]
