# Generated by Django 4.2 on 2024-04-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0015_autoscrapauthoritem_fail_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='avatar_link',
            new_name='image_link',
        ),
    ]
