# Generated by Django 4.2 on 2024-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0016_rename_avatar_link_author_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='<django.db.models.fields.CharField>.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='<django.db.models.fields.CharField>.png', upload_to='images/'),
        ),
    ]
