# Generated by Django 4.2 on 2024-04-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0017_alter_author_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='PostSearchDailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is scraped')),
                ('fail_count', models.IntegerField(default=0, verbose_name='Fail count')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_search_daily_items', to='techcrunch.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Search Daily Item',
                'verbose_name_plural': 'Post Search Daily Items',
            },
        ),
    ]
